### ISSUE TITLE
Update to Latest Bulma v1 

### ISSUE THREAD

**Issue by eleazarbr** [oruga-ui/theme-bulma#100]
Hello everyone,

I'm writing to request an update to be compatible with the latest version of Bulma version 1, which was released today (March 21, 2024). I understand that this has just been launched and the update might require some challenges. This issue is merely to bring it to our attention for future consideration.

Thanks and best regards.

**Comment by lucraraujo** [comment]
According to the release notes, V1 should be a drop-in replacement for 0.9.4.

**Comment by messenjer** [comment]
Hello,

For one of my projects, I had the necessity to customize the entire Oruga Bulma theme using CSS variables. Consequently, instead of utilising Oruga's theme-bulma, I opted for the Bulvar library available at https://github.com/daniil4udo/bulvar for the Buefy project. However, if the Oruga theme-bulma were to upgrade to the latest version of Bulma (version 1) with built-in support for CSS variables, it would eliminate the need for Bulvar.

To upgrade to bulma v1 we need also to replace all the `@import` by `@use` or `@forward ` and setup correctly the variables inside the `theme-bulma`. There is an old pull request here: https://github.com/oruga-ui/theme-bulma/pull/49 by @IceBlizz6 . It might help to port this PR to the master branch. 

Mathieu

**Comment by messenjer** [comment]
I created a PR to replace @import with @use, @forward https://github.com/oruga-ui/theme-bulma/pull/101 a step towards bulma v1

**Comment by messenjer** [comment]
I try to upgrade to 1.0 from my PR #101, here is the first commit : 

https://github.com/messenjer/theme-bulma/pull/1/commits/ff63035ff89855a46766ce7a0e40dd73570c568b

There are sass variables from bulma 0.9 used in theme-bulma that have been renamed, or calculated differently in bulma 1.0.

Example : 

* `$input-background-color` --> `hsl( $input-h,  $input-s, calc(input-background-l + input-background-l-delta))`

Here: https://github.com/jgthms/bulma/blob/d2687d444c907893a6feb8733404364b871a94d5/sass/form/shared.scss#L97 

```
  background-color: hsl(
    #{cv.getVar("input-h")},
    #{cv.getVar("input-s")},
    calc(
      #{cv.getVar("input-background-l")} + #{cv.getVar(
          "input-background-l-delta"
        )}
    )
  );
```

There will be a lot of work to do, perhaps we should ask for advice on the bulma project to get recommendations and help.

**Comment by messenjer** [comment]
@mlmoravek Congratulations on this work, looking forward to the release ;-)
