### ISSUE TITLE
Issue with 0.4.2 & @oruga-ui/oruga-next

### ISSUE THREAD

**Issue by srozen** [oruga-ui/theme-bulma#136]
Hello,

I suspect an issue regarding the `0.4.2` release.
`@oruga-ui/oruga-next` is marked as peer dependency on version `0.9.0-pre.1`, and also as a devDependency on version `0.9.0-pre.2`.

On projects that uses `@oruga-ui/theme-bulma` as a dependency, multiple calls to `{ isTrueish } from '@oruga-ui/oruga-next'` are made. 
These are not resolvable as this helper function is not made available in the `dist` of `@oruga-ui/oruga-next` version `0.9.0-pre.1`.

**Comment by mlmoravek** [comment]
Oh yeah, that might be true, thanks for the feedback! 

Adding Oruga as a peer dependency was an experiment to help with better type support and so on. But it seems I added the from version, thanks.

Will be fixed in the next version. However, I'm going to focus on some main oruga updates first, if this issue isn't a showstopper for you?

**Comment by climentjoan** [comment]
Hello,

I'm also stuck with this problem, I can't get working version 0.4.* (because isTrueish). I tried 0.3.0, and I got the theme working, but I got a lot of errors like TypeError: Cannot read properties of undefined (reading 'size') in selects, pagination... So I can't use the theme in any version.

Regards

**Comment by srozen** [comment]
Hello @mlmoravek, thanks for your quick answer! :)

Well, it is quite a problem for us I must say, and would be very delighted if you were able to release this fix 🙏 

Cheers

**Comment by mlmoravek** [comment]
So the fix will be to update the peer dependency to 0.9.0-pre.2, right ? 
Or what would you expect?
